export const hospitalsData = [
  {
    shortName: 'Acıbadem',
    fullTitle: 'Acıbadem Sağlık Grubu Hastanesi',
    authorizedPerson: 'Dr. Ahmet Yılmaz',
    city: 'İstanbul',
    district: 'Kadıköy',
    phone: '02163456789',
    email: 'info@acibadem.com',
    address: 'Bağdat Cad. No:123 Kadıköy/İstanbul',
    taxNumber: '1234567890',
    taxOffice: 'Kadıköy',
    website: 'https://www.acibadem.com',
    status: 'active',
    createdAt: '2023-01-15'
  },
  {
    shortName: 'Medipol',
    fullTitle: 'Medipol Mega Üniversite Hastanesi',
    authorizedPerson: 'Dr. Elif Demir',
    city: 'İstanbul',
    district: 'Bağcılar',
    phone: '02169876543',
    email: 'info@medipol.com',
    address: 'TEM Avrupa Otoyolu Göztepe Çıkışı No:1 Bağcılar/İstanbul',
    taxNumber: '9876543210',
    taxOffice: 'Bağcılar',
    website: 'https://www.medipol.com',
    status: 'active',
    createdAt: '2022-11-20'
  },
  {
    shortName: 'Ege',
    fullTitle: 'Ege Üniversitesi Tıp Fakültesi Hastanesi',
    authorizedPerson: 'Dr. Mehmet Kaya',
    city: 'İzmir',
    district: 'Bornova',
    phone: '02324567890',
    email: 'info@egehastanesi.com',
    address: 'Ege Üniversitesi Kampüsü Bornova/İzmir',
    taxNumber: '4567891230',
    taxOffice: 'Bornova',
    website: 'https://www.egehastanesi.com',
    status: 'pasive',
    createdAt: '2021-06-10'
  },
  {
    shortName: 'Memorial',
    fullTitle: 'Memorial Şişli Hastanesi',
    authorizedPerson: 'Dr. Ayşe Çelik',
    city: 'İstanbul',
    district: 'Şişli',
    phone: '02122223344',
    email: 'info@memorial.com',
    address: 'Piyalepaşa Bulvarı No:4 Şişli/İstanbul',
    taxNumber: '3216549870',
    taxOffice: 'Şişli',
    website: 'https://www.memorial.com',
    status: 'active',
    createdAt: '2023-03-05'
  },
  {
    shortName: 'Başkent',
    fullTitle: 'Başkent Üniversitesi Ankara Hastanesi',
    authorizedPerson: 'Dr. Canan Yıldız',
    city: 'Ankara',
    district: 'Çankaya',
    phone: '03124561234',
    email: 'info@baskenthastanesi.com',
    address: 'Mithatpaşa Cad. No:64 Çankaya/Ankara',
    taxNumber: '7418529630',
    taxOffice: 'Çankaya',
    website: 'https://www.baskenthastanesi.com',
    status: 'active',
    createdAt: '2022-09-12'
  }
]; 